### ISSUE TITLE
Since the new fix...

### ISSUE THREAD

**Issue by jmwebgeek** [timdouglas/sublime-less2css#119]
I have been getting this error on Sublime 2...

Writing file widget.less with encoding UTF-8
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 362, in run_
  File ".\less2css.py", line 47, in run
  File ".\lesscompiler.py", line 90, in convertOne
  File ".\lesscompiler.py", line 193, in convertLess2Css
ValueError: zero length field name in format

**Comment by mattseymour** [comment]
@jmwebgeek can you please run the equivalent lessc command to see if you get any errors?

**Comment by mattseymour** [comment]
@jmwebgeek didnt realise how limited st2 is. I think the issue has been solved. You might need to update or reload sublime before changes take effect.

**Comment by jmwebgeek** [comment]
Just tested. Works. Thanks.
