### ISSUE TITLE
compile with error: AttributeError: 'bool' object has no attribute 'rfind'

### ISSUE THREAD

**Issue by VanMess** [timdouglas/sublime-less2css#128]
I had receive an error like this:
```
[less2css] Converting /Users/van/coding/less-test/index.less to /Users/van/coding/less-test/index.css
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./less2css.py", line 47, in run
  File "./lesscompiler.py", line 92, in convertOne
  File "./lesscompiler.py", line 226, in convertLess2Css
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py", line 623, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py", line 1141, in _execute_child
    raise child_exception
AttributeError: 'bool' object has no attribute 'rfind'
```

It's confusing,so how to fix this?Waiting online,tks.

**Comment by mattseymour** [comment]
Can you confirm to me the version of Sublime you are using and OS version.

Thanks
