### ISSUE TITLE
After automatic upgrade, less2css is not working

### ISSUE THREAD

**Issue by karlolaf** [timdouglas/sublime-less2css#142]
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "less2css in C:\Users\...\AppData\Roaming\Sublime Text 3\Installed Packages\Less2Css.sublime-package", line 57, in run
AttributeError: 'Compiler' object has no attribute 'convert_one'
Unable to open /C/Users/.../AppData/Roaming/Sublime Text 3/Packages/Less2Css/less2css.sublime-settings

**Comment by karlolaf** [comment]
Ok, error cleared after uninstalling and re-installing less2css plugin.
