### ISSUE TITLE
Value requires an array argument on line null

### ISSUE THREAD

**Issue by thebeeph** [timdouglas/sublime-less2css#160]
After update to Sublime Build 3124, when I go to save the less file, I get the following error:

SyntaxError: Value requires an array argument in [path]/main.less on line null, column 0:
1 @lightGreen: #839e8e;

It appears there's an issue reading the first line of the less file.

**Comment by tonister** [comment]
Hey, I don't think this is a Sublime issue. It suddenly started happening to me too on Cloud9.

I'm using gulp-less to compile the LESS files. 

```
tonister:~/workspace (master) $ gulp less
[08:20:44] Using gulpfile ~/workspace/gulpfile.js
[08:20:44] Starting 'less'...
[08:20:44] { Error: Value requires an array argument
    at Value (/home/ubuntu/workspace/node_modules/less/lib/less/tree/value.js:6:15)
    at Media (/home/ubuntu/workspace/node_modules/less/lib/less/tree/media.js:14:21)
    at Object.media (/home/ubuntu/workspace/node_modules/less/lib/less/parser/parser.js:1375:29)
    at Object.directive (/home/ubuntu/workspace/node_modules/less/lib/less/parser/parser.js:1431:67)
    at Object.primary (/home/ubuntu/workspace/node_modules/less/lib/less/parser/parser.js:264:92)
    at Object.block (/home/ubuntu/workspace/node_modules/less/lib/less/parser/parser.js:1107:63)
    at Object.media (/home/ubuntu/workspace/node_modules/less/lib/less/parser/parser.js:1367:34)
    at Object.directive (/home/ubuntu/workspace/node_modules/less/lib/less/parser/parser.js:1431:67)
    at Object.primary (/home/ubuntu/workspace/node_modules/less/lib/less/parser/parser.js:264:92)
    at Object.parse (/home/ubuntu/workspace/node_modules/less/lib/less/parser/parser.js:133:61)
  type: 'Syntax',
  filename: '/home/ubuntu/workspace/src/less/styles.less',
  index: undefined,
  line: null,
  callLine: NaN,
  callExtract: undefined,
  column: -1,
  extract: [ undefined, undefined, '@color-primary: #333;' ],
  message: 'Value requires an array argument in file /home/ubuntu/workspace/src/less/styles.less line no. null',
  stack: 'Error: Value requires an array argument\n    at Value (/home/ubuntu/workspace/node_modules/less/lib/less/tree/value.js:6:15)\n    at Media (/home/ubuntu/workspace/node_modules/less/lib/less/tree/media.js:14:21)\n    at Object.media (/home/ubuntu/workspace/node_modules/less/lib/less/parser/parser.js:1375:29)\n    at Object.directive (/home/ubuntu/workspace/node_modules/less/lib/less/parser/parser.js:1431:67)\n    at Object.primary (/home/ubuntu/workspace/node_modules/less/lib/less/parser/parser.js:264:92)\n    at Object.block (/home/ubuntu/workspace/node_modules/less/lib/less/parser/parser.js:1107:63)\n    at Object.media (/home/ubuntu/workspace/node_modules/less/lib/less/parser/parser.js:1367:34)\n    at Object.directive (/home/ubuntu/workspace/node_modules/less/lib/less/parser/parser.js:1431:67)\n    at Object.primary (/home/ubuntu/workspace/node_modules/less/lib/less/parser/parser.js:264:92)\n    at Object.parse (/home/ubuntu/workspace/node_modules/less/lib/less/parser/parser.js:133:61)',
  lineNumber: null,
  fileName: '/home/ubuntu/workspace/src/less/styles.less',
  name: 'Error',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-less' }
```

**Comment by jedidrew42** [comment]
I am using ATOM on Mac trying to compile my less variables.

`PluginError: Value requires an array argument
    at new Value (/Users/jamesnorman/Documents/master/gulp/best-practice/node_modules/less/dist/less.cjs.js:1448:19)
    at new Media (/Users/jamesnorman/Documents/master/gulp/best-practice/node_modules/less/dist/less.cjs.js:3604:26)
    at Object.media (/Users/jamesnorman/Documents/master/gulp/best-practice/node_modules/less/dist/less.cjs.js:8255:29)
    at Object.atrule (/Users/jamesnorman/Documents/master/gulp/best-practice/node_modules/less/dist/less.cjs.js:8334:67)
    at Object.primary (/Users/jamesnorman/Documents/master/gulp/best-practice/node_modules/less/dist/less.cjs.js:6879:95)
    at Object.block (/Users/jamesnorman/Documents/master/gulp/best-practice/node_modules/less/dist/less.cjs.js:7883:63)
    at Object.media (/Users/jamesnorman/Documents/master/gulp/best-practice/node_modules/less/dist/less.cjs.js:8250:34)
    at Object.atrule (/Users/jamesnorman/Documents/master/gulp/best-practice/node_modules/less/dist/less.cjs.js:8334:67)
    at Object.primary (/Users/jamesnorman/Documents/master/gulp/best-practice/node_modules/less/dist/less.cjs.js:6879:95)
    at Object.parse (/Users/jamesnorman/Documents/master/gulp/best-practice/node_modules/less/dist/less.cjs.js:6750:60) {
  message: 'Value requires an array argument in file /Users/jamesnorman/Documents/master/gulp/best-practice/src/less/best-practices.less line no. null',
  stack: 'Error: Value requires an array argument\n' +
    '    at new Value (/Users/jamesnorman/Documents/master/gulp/best-practice/node_modules/less/dist/less.cjs.js:1448:19)\n' +
    '    at new Media (/Users/jamesnorman/Documents/master/gulp/best-practice/node_modules/less/dist/less.cjs.js:3604:26)\n' +
    '    at Object.media (/Users/jamesnorman/Documents/master/gulp/best-practice/node_modules/less/dist/less.cjs.js:8255:29)\n' +
    '    at Object.atrule (/Users/jamesnorman/Documents/master/gulp/best-practice/node_modules/less/dist/less.cjs.js:8334:67)\n' +
    '    at Object.primary (/Users/jamesnorman/Documents/master/gulp/best-practice/node_modules/less/dist/less.cjs.js:6879:95)\n' +
    '    at Object.block (/Users/jamesnorman/Documents/master/gulp/best-practice/node_modules/less/dist/less.cjs.js:7883:63)\n' +
    '    at Object.media (/Users/jamesnorman/Documents/master/gulp/best-practice/node_modules/less/dist/less.cjs.js:8250:34)\n' +
    '    at Object.atrule (/Users/jamesnorman/Documents/master/gulp/best-practice/node_modules/less/dist/less.cjs.js:8334:67)\n' +
    '    at Object.primary (/Users/jamesnorman/Documents/master/gulp/best-practice/node_modules/less/dist/less.cjs.js:6879:95)\n' +
    '    at Object.parse (/Users/jamesnorman/Documents/master/gulp/best-practice/node_modules/less/dist/less.cjs.js:6750:60)',
  type: 'Syntax',
  filename: '/Users/jamesnorman/Documents/master/gulp/best-practice/src/less/best-practices.less',
  index: undefined,
  line: null,
  column: -1,
  callLine: NaN,
  callExtract: undefined,
  extract: [ undefined, undefined, undefined ],
  lineNumber: null,
  fileName: '/Users/jamesnorman/Documents/master/gulp/best-practice/src/less/best-practices.less',
  name: 'Error',
  plugin: 'gulp-less',
  showProperties: true,
  showStack: false`

**Comment by jedidrew42** [comment]
Does anyone know how to fix this error?
