### ISSUE TITLE
The 'shadow' option doesn't make sense.

### ISSUE THREAD

**Issue by vrbvillor** [timdouglas/sublime-less2css#166]
```
Writing file /E/alading/statics/less/news/news.less with encoding UTF-8
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 362, in run_
    return self.run(edit)
  File ".\less2css.py", line 57, in run
  File ".\lesscompiler.py", line 156, in convert_one
  File ".\lesscompiler.py", line 235, in convertLess2Css
ValueError: zero length field name in format
Package Control: No updated packages
```

This is the error page.

```
project
   less
      news
         news.less
   css
```
This is the file structure.

When I saved news.less, it tells the error message like above.

**Comment by vrbvillor** [comment]
I've posted this issue long time ago.  When I first use less2css plugin,  the 'shadow' worked well.  But after a certain version it updated and fail.  I fall back to the certain version and used this plugin for a long time.  But now I've forgotten the version's number.  I download the file of df4044e3c98f24cd41ba399125296836b11082f5 ,  it works.
