### ISSUE TITLE
[WARNING] Please install gem 'therubyracer' to use Less.

### ISSUE THREAD

**Issue by jedidrew42** [timdouglas/sublime-less2css#183]
`[WARNING] Please install gem 'therubyracer' to use Less.

I am getting this error when I try to compile a less file. I ran lessc <filename.less>

Help is appreciated.

Traceback (most recent call last):
	15: from /usr/local/bin/lessc:23:in `<main>'
	14: from /usr/local/bin/lessc:23:in `load'
	13: from /Library/Ruby/Gems/2.6.0/gems/less-2.6.0/bin/lessc:3:in `<top (required)>'
	12: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	11: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	10: from /Library/Ruby/Gems/2.6.0/gems/less-2.6.0/lib/less.rb:9:in `<top (required)>'
	 9: from /Library/Ruby/Gems/2.6.0/gems/less-2.6.0/lib/less.rb:14:in `<module:Less>'
	 8: from /Library/Ruby/Gems/2.6.0/gems/less-2.6.0/lib/less.rb:14:in `new'
	 7: from /Library/Ruby/Gems/2.6.0/gems/less-2.6.0/lib/less/loader.rb:13:in `initialize'
	 6: from /Library/Ruby/Gems/2.6.0/gems/less-2.6.0/lib/less/java_script.rb:17:in `context_wrapper'
	 5: from /Library/Ruby/Gems/2.6.0/gems/less-2.6.0/lib/less/java_script.rb:9:in `default_context_wrapper'
	 4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /Library/Ruby/Gems/2.6.0/gems/less-2.6.0/lib/less/java_script/v8_context.rb:2:in `<top (required)>'
	 1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- v8 (LoadError)`

**Comment by Ajrirfatima** [comment]
Did you get a solution?
