### ISSUE TITLE
Install LESSC in windows.

### ISSUE THREAD

**Issue by carlosbaraza** [timdouglas/sublime-less2css#2]
Hello, I am having some troubles to compile .less with your plugin because I do not have lessc installed in Windows. The plugin fails on the line 34, trying to execute the lessc command.

Console log this:

Traceback (most recent call last):
  File ".\sublime_plugin.py", line 362, in run_
  File ".\less2css.py", line 82, in run
  File ".\less2css.py", line 34, in convertOne
  File ".\subprocess.py", line 633, in **init**
  File ".\subprocess.py", line 842, in _execute_child
WindowsError: [Error 2] The system cannot find the file specified

Hope you could told me how to install lessc. Thank you for this great package

**Comment by ltsharma** [comment]
awesome Tikot, it worked for me too... Thank you

**Comment by nighinatt** [comment]
Thanks tikot
It Worked for me tooo...
