### ISSUE TITLE
less2css error: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by neilmalgaonkar** [timdouglas/sublime-less2css#51]
Hi, 
I am having problem with less2css on my Mac OS 10.7.

I have installed less2css on sublime 2. but for no reason its giving me following error.

"less2css error: [Errno 2] No such file or directory"

I tried to debug the code and I came to following conclusion
 code is failing at 
"p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)" in "convertLess2Css" in "lesscompiler.py"

First I thought It is coming because of encoding issue for file paths , so I fixed the path with encoding them with "utf-8". But still it shows up.
I also tried the same command from command line and it worked perfectly no error nothing it executed perfectly.
So Right now I am clueless about it , could you help me out in this issue.

Exception that I got is

**error: less2css error: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./less2css.py", line 39, in run
    MessageWindow(resp)
  File "./less2css.py", line 14, in **init**
    self.show(message)
  File "./less2css.py", line 27, in show
    sublime.error_message(message)
Boost.Python.ArgumentError: Python argument types in
    sublime.error_message(NoneType)
did not match C++ signature:
    error_message(std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >)**

Thanks!

**Comment by gregbown** [comment]
So here we are in 2021
Tried the path to lessc in the "lessCommand" user settings and it did not work.
Removed it and put "lessCommand" back to false, then...
Set an environment path to lessc in Windows Environment Variables, restarted and now it works
