### ISSUE TITLE
error: less2css error: `lessc` is not available

### ISSUE THREAD

**Issue by kelvinlee** [timdouglas/sublime-less2css#61]
Writing file /Users/sumomofukeqiao/Kelvin_app/Work/Pureit/html/static/css/test.less with encoding UTF-8 (atomic)
[less2css] Converting /Users/sumomofukeqiao/Kelvin_app/Work/Pureit/html/static/css/test.less to /Users/sumomofukeqiao/Kelvin_app/Work/Pureit/html/static/css/test.css
error: less2css error: `lessc` is not available
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "less2css in /Users/sumomofukeqiao/Library/Application Support/Sublime Text 3/Installed Packages/Less2Css.sublime-package", line 46, in run
  File "less2css in /Users/sumomofukeqiao/Library/Application Support/Sublime Text 3/Installed Packages/Less2Css.sublime-package", line 14, in __init__
  File "less2css in /Users/sumomofukeqiao/Library/Application Support/Sublime Text 3/Installed Packages/Less2Css.sublime-package", line 21, in show
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime.py", line 866, in get
    return sublime_api.settings_get_default(self.settings_id, key, default)
TypeError: Value required

My sublime text 3 install less2css, but when I save .less files always alert.
"less2css error: `lessc` is not available".

I install nodejs and less.
![image](https://f.cloud.github.com/assets/2314674/786617/7a06ab0a-eabe-11e2-917b-1ed2a25b8e19.png)

**Comment by zilingxingzi** [comment]
sing @PGBI On Mac OS X Yosemite:
Useful to know: which node and which lessc
To make it work :

Add "lesscCommand": "/Users/<yourusername>/.node/bin/lessc", line to Preferences > Package Settings > Less2Css > Settings User

If error : "env: node: No such file or directory"
then :
sudo ln -s /usr/local/bin/node /usr/bin/node

**Comment by gregbown** [comment]
So here we are in 2021
Tried the path to lessc in the "lessCommand" user settings and it did not work.
Removed it and put "lessCommand" back to false, then...
Set an environment path to lessc in Windows Environment Variables, restarted and now it works
