### ISSUE TITLE
UnicodeDecodeError : UTF8

### ISSUE THREAD

**Issue by SpiStache** [timdouglas/sublime-less2css#87]
Hello,

I can't find how to solve this issue, if someone know the answer, this should be great.

I'm using windows 8, node.js installed

Writing file /C/wamp/www/Portfolio/css/style.less with encoding UTF-8
[less2css] Converting C:\wamp\www\Portfolio\css\style.less to C:\wamp\www\Portfolio\css\style.css
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 362, in run_
  File ".\less2css.py", line 47, in run
  File ".\lesscompiler.py", line 89, in convertOne
  File ".\lesscompiler.py", line 223, in convertLess2Css
  File ".\encodings\utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0x82 in position 111: unexpected code byte

**Comment by kristofferdarj** [comment]
Something similar here.
Win 7 with node.js and less installed via node.

Writing file /C/Dropbox/dev/htdocs/h1_portal/public_html/app/webroot/css/style.less with encoding UTF-8
[less2css] Converting C:\Dropbox\dev\htdocs\h1_portal\public_html\app\webroot\css\style.less to C:\Dropbox\dev\htdocs\h1_portal\public_html\app\webroot\css\style.css
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 362, in run_
    return self.run(edit)
  File ".\less2css.py", line 47, in run
  File ".\lesscompiler.py", line 89, in convertOne
  File ".\lesscompiler.py", line 223, in convertLess2Css
  File ".\encodings\utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0x84 in position 53: unexpected code byte
